<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>ToolBX.AutoInject</RootNamespace>
		<RepositoryUrl>https://github.com/Moreault/AutoInject</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<Authors>Mathieu Moreault</Authors>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Version>4.0.0</Version>
		<Description>A .NET library to make it easier to use DI by adding [AutoInject] attributes directly on classes.</Description>
		<PackageId>ToolBX.$(AssemblyName)</PackageId>
		<PackageIcon>autoinject.png</PackageIcon>
		<PackageProjectUrl>https://github.com/Moreault/AutoInject</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <IsAotCompatible>True</IsAotCompatible>
	  <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	  <IsTrimmable>False</IsTrimmable>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <IsAotCompatible>True</IsAotCompatible>
	  <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	  <IsTrimmable>False</IsTrimmable>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AutoInject.Generators\AutoInject.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\AutoInject.Generators\bin\$(Configuration)\netstandard2.0\AutoInject.Generators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<None Update="autoinject.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>
